sudo: required
dist: trusty
env:
  global:
    - TESTLINK_URL=http://qalab.tk:86
    - TESTLINK_DEV_KEY=ae2f4839476bea169f7461d74b0ed0ac
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
- pip freeze
install:
- python setup.py install
script:
- python setup.py test
after_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      sonar-scanner -X -Dsonar.login=${SONAR_GITHUB_TOKEN} -Dsonar.host.url=http://qalab.tk:82 ;
  else
      sonar-scanner -X -Dsonar.login=${SONAR_GITHUB_TOKEN} -Dsonar.host.url=http://qalab.tk:82 -Dsonar.github.repository=netzulo/qatestlink -Dsonar.github.pullRequest=${TRAVIS_PULL_REQUEST} -Dsonar.github.oauth=${GITHUB_TOKEN} -Dsonar.analysis.mode=preview ;
  fi
